version: '3'

services:
  app:
    container_name: node
    image: node:1.0
    tty: true
    volumes:
      - ../server:/hoticeamericano
    ports:
      - 8080:8080
      - 9229:9229
    command: bash -c "yarn && yarn dev"
    init: true
  
  pg:
    container_name: pg
    image: postgres:12.8-alpine3.14
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ../db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432